### ISSUE TITLE
`save-state` and `set-output` are deprecated

### ISSUE THREAD

**Issue by netanelrabinowitz** [aws-actions/amazon-ecr-login#358] opened 2022-10-12 21:22 UTC
The action yields the following warning 

```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Should resolve once `dependabot` pr #352 find it's way to the next release

**Comment by renperez-cpi** [comment] 2022-10-13 06:16
same issue
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by CaBazaga** [comment] 2022-10-24 12:19
> The action yields the following warning
> 
> ```
> Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> ```
> 
> Should resolve once `dependabot` pr #352 find it's way to the next release

Both deprecated statements are also present on this own repo code:

https://github.com/aws-actions/amazon-ecr-login/blob/cad9b9ce1d5b06e60ee95d1240e6cf3d69074b32/dist/cleanup/index.js#L2819

https://github.com/aws-actions/amazon-ecr-login/blob/cad9b9ce1d5b06e60ee95d1240e6cf3d69074b32/dist/cleanup/index.js#L2948

**Comment by joekhoobyar** [comment] 2022-10-25 19:57
I can confirm, if running this workflow from it's `main` branch, the warnings go away for me.

**Comment by mdouglass** [comment] 2022-10-25 22:45
> I can confirm, if running this workflow from it's `main` branch, the warnings go away for me.

Same for me -- looks like a dependabot update of @actions/core just landed on main which fixed the issue. So if there is a new release done, we should be gtg.

**Comment by TzlilSwimmer123** [comment] 2022-10-27 12:17
@mdouglass do you know when the new release suppose to happen?

**Comment by arjraman** [comment] 2022-10-29 06:35
@mdouglass @TzlilSwimmer123 @joekhoobyar @CaBazaga @renperez-cpi @netanelrabinowitz apologize for the delay, should be released now!

**Closed as completed** 2022-10-31 22:25 UTC
Labels: dependencies
